### ISSUE TITLE
Error messages are confusing.

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Library-Initial-Community#4]
The error messages need adjustment. In this case, the AGB was too high, but the error message says it's a problem with "Age" and then it says biomass has to be between 0% and 100%. Basically it should say: Error message with the input value for AGB AND 111948 is not between 0 and 40,000, or whatever max you want to use.

2019-11-13 14:59:14,472 -    Loading initial communities from file "AK_IC_File-SW_111019.txt" ...
2019-11-13 14:59:14,494 - Error at line 7 of file "AK_IC_File-SW_111019.txt":
  Error with the input value for Age:
    "(111943" is not a valid aboveground biomass input:
      111943 is not between 0% and 100%

**Comment by rmscheller** [comment]
I updated the error messages but it needs to be tested before posting to the Support repo.  Could you compile and test?

**Comment by mslucash** [comment]
I don't see the code changes. When I look in this repo, there weren't any changes to the code in Nov, except for the project and ReadMe. What am I missing?

**Comment by rmscheller** [comment]
The changes are in a branch:  https://github.com/LANDIS-II-Foundation/Library-Initial-Community/tree/InputBiomass

**Comment by mslucash** [comment]
But there weren't any changes in the the main or branch in Nov. I'm still confused.
Do I need to recompile the Succession library or just DGS? 
![NoChangesIC](https://user-images.githubusercontent.com/7819936/71855483-02e4d400-3096-11ea-8446-6ef7e3555b8c.PNG)

**Comment by rmscheller** [comment]
Ah, yes, I see.  The code was not fully synced.  Should be ready for testing now.

**Comment by mslucash** [comment]
So I couldn't get it run at all. Versioning issue?

![image](https://user-images.githubusercontent.com/7819936/72122243-17cd9b80-3312-11ea-9080-b359e6693cdb.png)

**Comment by rmscheller** [comment]
I wouldn't think so.  Let's chat on the phone when you can.  Will you be in this morning?  I'm out after 11am eastern.

**Comment by mslucash** [comment]
Runs now!  That fixed it.  Biomass in txt file matches csv. 
Still a minor issue with the error message. Says it's an error with the "input value for Age", when it's an error in the biomass. I tried to fix it myself, but I couldn't find the error. 
![Age_ICbranch](https://user-images.githubusercontent.com/7819936/72181394-1b0e6900-339e-11ea-8c77-a5a9916ed5bc.PNG)

**Comment by rmscheller** [comment]
I made a couple of very minor tweaks to clean up the error messages.  Could you test again?  Thanks!

**Comment by mslucash** [comment]
Works now. It's not perfect, but close enough.  Minor error is that it says "Error with the input value for AGE..."
but it's followed by correct language that it's an issue with AGB. Good enough for me.
[Landis-log.txt](https://github.com/LANDIS-II-Foundation/Library-Initial-Community/files/4099378/Landis-log.txt)
